const DEVELOPMENT = 'development';
const PRODUCTION = 'production';
const BOARD_NAME_MIN_LENGTH = 1;
const BOARD_NAME_MAX_LENGTH = 30;
const THREAD_MIN_LENGTH = 1;
const THREAD_MAX_LENGTH = 124;
const PASSWORD_MIN_LENGTH = 5;
const PASSWORD_MAX_LENGTH = 15;
const REPLY_MIN_LENGTH = THREAD_MIN_LENGTH;
const REPLY_MAX_LENGTH = 1500;
const DEFAULT_REPLY_LIMIT = 1000;
const BOARDS = ['general'];

module.exports = {
  DEVELOPMENT,
  PRODUCTION,
  BOARD_NAME_MIN_LENGTH,
  BOARD_NAME_MAX_LENGTH,
  THREAD_MIN_LENGTH,
  THREAD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  REPLY_MIN_LENGTH,
  REPLY_MAX_LENGTH,
  DEFAULT_REPLY_LIMIT,
  BOARDS
};